### ISSUE TITLE
推送不正常

### ISSUE THREAD

**Issue by homileak** [benx1n/when2holiday#3]
非常感谢您的插件，不过我在部署插件的时候遇到了问题。
部署过程正常无报错。
部署完成后发现机器人不推送，hoshino后台正常无报错，看不出问题。
手动发送“测试假期推送”机器人仍然没有反应。
“剩余假期”命令正常。
以下是hoshino的后台输出：
[2022-04-30 20:21:04,102 nonebot] INFO: Self: 684215673, Message -1475135976 from 975213875@[群:864125637]: '测试假期推送'
[2022-04-30 20:21:04,103 when2holiday] INFO: Message -1475135976 triggered send_holiday_message.
https://timor.tech/api/holiday/info
2
[2022-04-30 20:21:04,826 nonebot] INFO: Message -1475135976 is ignored: Handled by Hoshino

![4732](https://user-images.githubusercontent.com/48946260/166106320-24f8928b-1c4c-42ef-93f5-7a4e33875ed2.png)

**Comment by benx1n** [comment]
是我偷懒了 没有对节假日做适配，引用接口的描述
"type": enum(0, 1, 2, 3), // 节假日类型，分别表示 工作日、周末、节日、调休。
理论上周末和节日也不需要摸鱼推送吧233
已经更新为休息日不推送，但可通过“测试假期推送”获得返回，请拉取最新代码尝试

**Comment by homileak** [comment]
> 是我偷懒了 没有对节假日做适配，引用接口的描述 "type": enum(0, 1, 2, 3), // 节假日类型，分别表示 工作日、周末、节日、调休。 理论上周末和节日也不需要摸鱼推送吧233 已经更新为休息日不推送，但可通过“测试假期推送”获得返回，请拉取最新代码尝试

非常感谢您的回复！
拉取新的代码后机器人正常回应“测试假期推送”了。


对了，想顺便问一下您，使用什么命令才能达到您图中的效果呢？没有别的意思，我只是想确保一下插件在正常工作，因为为最近5天都是休息日，如果一直等到休息日结束才能测试的话，时间就拉的有点太久了。
![7067](https://user-images.githubusercontent.com/48946260/166106918-8f28b2e2-dbad-47bd-8165-1452713aea39.jpg)

**Comment by benx1n** [comment]
修改了“测试假期推送”指令，现在可带上日期用于获取指令日期的推送消息，默认为上午9点
请拉取最新代码尝试

**Comment by homileak** [comment]
> 修改了“测试假期推送”指令，现在可带上日期用于获取指令日期的推送消息，默认为上午9点 请拉取最新代码尝试

多谢回复！拉取新的代码后，测试插件工作一切正常。

非常感谢您开发摸鱼插件，祝您生活愉快，日日有鱼摸！ XD
